name: Run application and commit .ics

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main # check out ics branch
      - name: Create .ics file
        run: |
          npm install
          npm start
      - name: Configure Git
        run: |
          git config --global user.name "Will Nguyen"
          git config --global user.email "101022886+wqngyn@users.noreply.github.com"
      - name: Push .ics file to repository
        run: |
          git add ./exports/UFC.ics
          git commit -m "Update .ics file"
          git push -u origin main
